<a href="https://colab.research.google.com/github/hinsley/colabs/blob/master/Backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

np.random.seed(0)

In [2]:
# Bias weights are always zero-indexed in each node's array. Bias weight is not
# counted into layer sizes.

input_size = 5

layer_sizes = [5, 10, 3]

nn_list = [[[]] * input_size] # A bit wasteful computationally, but helps keep
                              # the initialization algorithm concise.
for layer_size in layer_sizes:
  # Note that each node has an additional weight initialized for its bias.
  nn_list.append([np.random.random(len(nn_list[-1]) + 1) for
                  node in
                  range(layer_size)])

del nn_list[0]

nn_list

[[array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
         0.64589411]),
  array([0.43758721, 0.891773  , 0.96366276, 0.38344152, 0.79172504,
         0.52889492]),
  array([0.56804456, 0.92559664, 0.07103606, 0.0871293 , 0.0202184 ,
         0.83261985]),
  array([0.77815675, 0.87001215, 0.97861834, 0.79915856, 0.46147936,
         0.78052918]),
  array([0.11827443, 0.63992102, 0.14335329, 0.94466892, 0.52184832,
         0.41466194])],
 [array([0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ,
         0.6176355 ]),
  array([0.61209572, 0.616934  , 0.94374808, 0.6818203 , 0.3595079 ,
         0.43703195]),
  array([0.6976312 , 0.06022547, 0.66676672, 0.67063787, 0.21038256,
         0.1289263 ]),
  array([0.31542835, 0.36371077, 0.57019677, 0.43860151, 0.98837384,
         0.10204481]),
  array([0.20887676, 0.16130952, 0.65310833, 0.2532916 , 0.46631077,
         0.24442559]),
  array([0.15896958, 0.11037514, 0.65632959, 0.13818295, 0.19658236,
         0

In [0]:
def feed_forward(network, inputs):
  """
  Here we use a typical densely-connected set of layers. I forget the term for
  this.
  """

  bias = 1.0

  def activation(input_):
    # We use ReLU here. I'm too lazy to come up with names that avoid keyword
    # conflicts.
    return 0 if input_ < 0 else input_

  def propagate(weight_matrix, inputs):
    """
    Perform matrix multiplication of weight matrix with inputs. Columns in
    weight_matrix and rows in inputs should be equal. We then run each result
    in the "potentials" vector through an activation function, finishing by
    prepending a constant bias term to the result vector.

    Note that this function assumes a bias has already been added to inputs,
    and is not able to discern whether its output should be the true output
    of the network (you will have to manually prune the bias term from the
    return value with `propagate(...)[1:]` or equivalent on the output layer).

    I know this docstring is kind of long for what this function actually
    accomplishes, but if you're a programmer and you can't be bothered to spend
    a minute reading from time to time then I've got bad news for you.

    Twas bryllyg, and the slythy toves
    Did gyre and gymble in the wabe:
    All mimsy were the borogoves;
    And the mome raths outgrabe.

    Jupyter desperately needs a block collapse feature.
    """

    potentials = np.matmul(weight_matrix, inputs)
    post_activation = [activation(potential) for potential in potentials]
    
    return np.concatenate(([bias], post_activation))

  current_values = np.concatenate(([bias], inputs))

  for layer in network:
    current_values = propagate(layer, current_values)
  
  return current_values[1:] # Remove bias from output.

In [4]:
inputs = np.random.random(input_size)

outputs = feed_forward(nn_list, inputs)

outputs

array([17.29065649, 27.35296662, 30.39293233])

In [5]:
def error(outputs, ideals):
  """We use root mean square error (RMSE) here."""
  return np.sum((ideals - outputs) ** 2) / outputs.size ** 0.5

ideals = np.array([0.5, 0.75, 0.825]) # I totally made this up.

error(outputs, ideals)

1076.1269774708546

In [0]:
# Now I've just got to implement the actual backprop algorithm, and some kind of
# batching procedure with test data. I'll do that whenever I get bored again.
# It's midnight.