<a href="https://colab.research.google.com/github/hinsley/colabs/blob/master/Pre_Swap_Gauss_Jordan_Elimination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook is pretty old and may not be perfect.

In [0]:
import numpy as np

example_matrix = np.array([[1.,0.,0.,0.,4.],[0.,1.,1.,0.,-1.],[0.,0.,1.,1.,-8.],[0.,1.,0.,0.,1.]])

print(example_matrix)

[[ 1.  0.  0.  0.  4.]
 [ 0.  1.  1.  0. -1.]
 [ 0.  0.  1.  1. -8.]
 [ 0.  1.  0.  0.  1.]]


In [0]:
from itertools import permutations

def gauss_jordan(matrix: np.array) -> np.array:
  t_matrix = np.copy(matrix)
                                                            
  def scale_row(a: int, c: float):
    t_matrix[a] *= c
                                                                            
  def add_scaled_row(a: int, b: int, c: float):
    # c*R_b + R_a -> R_a
    t_matrix[a] += c * t_matrix[b]
                                               
  possible_orders = permutations(range(len(t_matrix)))
                                                                                                            
  reducible = False
  for possible_order in possible_orders:
    if all([t_matrix[row][column] != 0 for column, row in enumerate(possible_order)]):
      t_matrix = np.array([t_matrix[row] for row in possible_order])
      reducible = True
      break                  
  if not reducible:
    raise ValueError("No solution found.")
                                                                                                                                                                                
  scale_row(0, 1 / t_matrix[0][0])
                                                                                                                                                                                    
  for row in range(1, len(t_matrix)):
    for column in range(row):
      add_scaled_row(row, column, -t_matrix[row][column])
    scale_row(row, 1 / t_matrix[row][row])
                                                                                                                                                                                                                            
  for row in range(len(t_matrix)):
    for column in range(row + 1, len(t_matrix[row]) - 1):
      add_scaled_row(row, column, -t_matrix[row][column])
                                                                                                                                                                                                                                                        
  return t_matrix.transpose()[-1]

In [0]:
print(gauss_jordan(example_matrix))

[ 4.  1. -2. -6.]
